### ISSUE TITLE
Error login version 6.45.6 - inicio de sesión heredado

### ISSUE THREAD

**Issue by egoan82** [pear2/Net_RouterOS#51]
Buen día para todos,

Tengo problemas para realizar el login desde el api con la ultima versión de routeros 6.45.6, me dice que el usuario y la contraseña son incorrectos.

Lo que he investigado es que desde la versión 6.43 hacia arriba un cambio en el inicio de sesión y al parecer hay que agregar el legacy en true.

Agradezco informen si se realizara una actualización o alguien de la comunidad tiene una solución.

Saludos desde Colombia.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Good day to all,

I have problems logging in from the api with the latest version of routers 6.45.6, it tells me that the username and password are incorrect.

What I have investigated is that from version 6.43 upwards a change in the login and apparently it is necessary to add the legacy to true.

I appreciate informing if an update will be made or someone from the community has a solution.

Greetings from Colombia.

![sshot-1](https://user-images.githubusercontent.com/29617555/65008860-54433a80-d8d0-11e9-9a63-7400ed56ddc0.png)

**Comment by wdjag** [comment]
1. use english
2. https://github.com/pear2/Net_RouterOS/issues/47

**Comment by egoan82** [comment]
Excelente con esto logre solucionar el problema de inicio de sesion.

Gracias por su amable colaboración, espero una nueva actualización de la librería.

Saludos desde Colombia.

Solución: https://github.com/pear2/Net_RouterOS/issues/47#issuecomment-510460031

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Excellent with this I managed to solve the login problem.

Thank you for your kind cooperation, I look forward to a new library update.

Greetings from Colombia.

Solution: https://github.com/pear2/Net_RouterOS/issues/47#issuecomment-510460031


![sshot-1](https://user-images.githubusercontent.com/29617555/65009010-d9c6ea80-d8d0-11e9-9c85-a8a4c031b1e9.png)
