### ISSUE TITLE
Error installing with composer

### ISSUE THREAD

**Issue by Luizgpp** [pear2/Net_RouterOS#57]
When i use 'composer require pear2/net_routeros:*@beta'
show this error:

Your requirements could not be resolved to an installable set of packages.

Problem 1

    - pear2/net_routeros 1.0.0b6 requires pear2/net_transmitter >=1.0.0b1 -> satisfiable by pear2/net_transmitter[1.0.0b1, 1.0.0b2, dev-master] but these conflict with your requirements or minimum-stability.

    - pear2/net_routeros 1.0.0b5 requires pear2/net_transmitter >=1.0.0a5 -> satisfiable by pear2/net_transmitter[1.0.0a5, 1.0.0b1, 1.0.0b2, dev-master] but these conflict with your requirements or minimum-stability.

    - pear2/net_routeros 1.0.0b4 requires pear2/net_transmitter >=1.0.0a4 -> satisfiable by pear2/net_transmitter[1.0.0a4, 1.0.0a5, 1.0.0b1, 1.0.0b2, dev-master] but these conflict with your requirements or minimum-stability.    - Installation request for pear2/net_routeros *@beta -> satisfiable by pear2/net_routeros[1.0.0b4, 1.0.0b5, 1.0.0b6].

Installation failed, deleting ./composer.json.

Why this happen?

**Comment by pavlyuts** [comment]
Hi!

Composeer wants stable (not beta) code and can't find it.

Put this into your composer.json file:

```
        "pear2/net_routeros": "dev-develop",
        "pear2/net_transmitter": "*@beta"
```

Please, mind that 1.0.0b6 has some bugs so dev-develop hihgly recommended. All of this works for me.

**Comment by Luizgpp** [comment]
Many thanks! i see "pear2/net_routeros": "dev-develop", in other issue and its works.

Thanks a lot!

**Comment by olgapatriciarios** [comment]
Thanks, At first I put pear2/net_transmitter y then pear2/net_routeros...  apparently it works... hugs from Bogotá.
